const urls = [
  ["./contributing.md", "image/others.svg"],
  ["#table-of-contents", "image/others.svg"],
  ["#ui-graphics", "image/others.svg"],
  ["#fonts", "image/others.svg"],
  ["#colors", "image/others.svg"],
  ["#icons", "image/icons.svg"],
  ["#logos", "image/others.svg"],
  ["#favicons", "image/others.svg"],
  ["#icon-fonts", "image/others.svg"],
  ["#stock-photos", "image/others.svg"],
  ["#stock-videos", "image/others.svg"],
  ["#stock-music--sound-effects", "image/others.svg"],
  ["#vectors--clip-art", "image/others.svg"],
  ["#product--image-mockups", "image/others.svg"],
  ["#html--css-templates", "image/others.svg"],
  ["#css-frameworks", "image/others.svg"],
  ["#css-methodologies", "image/others.svg"],
  ["#css-animations", "image/others.svg"],
  ["#javascript-animation-libraries", "image/others.svg"],
  ["#javascript-chart-libraries", "image/others.svg"],
  ["#ui-components--kits", "image/others.svg"],
  ["#react-ui-libraries", "image/react.svg"],
  ["#vue-ui-libraries", "image/others.svg"],
  ["#angular-ui-libraries", "image/angular.svg"],
  ["#svelte-ui-libraries", "image/others.svg"],
  ["#react-native-ui-libraries", "image/react.svg"],
  ["#design-systems--style-guides", "image/others.svg"],
  ["#online-design-tools", "image/others.svg"],
  ["#downloadable-design-software", "image/others.svg"],
  ["#design-inspiration", "image/others.svg"],
  ["#image-compression", "image/others.svg"],
  ["#chrome-extensions", "image/others.svg"],
  ["#others", "image/others.svg"],
  ["https://www.sinwaver.com/", "image/others.svg"],
  ["https://uidesigndaily.com/", "image/others.svg"],
  ["https://100dailyui.webflow.io/", "image/others.svg"],
  ["https://www.sketchappsources.com/", "image/others.svg"],
  ["https://www.humaaans.com/", "image/others.svg"],
  ["https://products.ls.graphics/paaatterns/", "image/others.svg"],
  ["http://thepatternlibrary.com/", "image/others.svg"],
  ["https://error404.fun/", "image/others.svg"],
  ["https://www.drawkit.io/", "image/others.svg"],
  ["https://absurd.design/", "image/others.svg"],
  ["https://undraw.co/", "image/others.svg"],
  ["https://www.manypixels.co/gallery/", "image/others.svg"],
  ["https://www.openpeeps.com/", "image/others.svg"],
  ["https://uispace.net/", "image/others.svg"],
  ["http://animaticons.co/", "image/others.svg"],
  ["https://www.uplabs.com/", "image/others.svg"],
  [
    "https://www.invisionapp.com/inside-design/design-resources/",
    "image/others.svg",
  ],
  ["https://www.opendoodles.com/", "image/others.svg"],
  ["https://avataaars.com/", "image/others.svg"],
  ["https://blush.design/", "image/others.svg"],
  ["http://www.heropatterns.com/", "image/others.svg"],
  ["https://patterns.beaubus.com/", "image/others.svg"],
  ["https://isoflat.com/", "image/others.svg"],
  ["https://iradesign.io/", "image/others.svg"],
  ["https://www.transparenttextures.com/", "image/others.svg"],
  ["https://icons8.com/illustrations", "image/others.svg"],
  ["https://patternico.com", "image/others.svg"],
  ["https://www.freellustrations.com/", "image/others.svg"],
  ["https://www.pixeltrue.com/illustrations", "image/others.svg"],
  ["https://www.abstractapi.com/user-avatar-api", "image/others.svg"],
  ["https://sketchvalley.com/", "image/others.svg"],
  ["https://patternpad.com/", "image/others.svg"],
  ["https://www.dimensions.com/", "image/others.svg"],
  ["https://freebiesbug.com/", "image/others.svg"],
  ["https://2.flexiple.com/scale/all-illustrations", "image/others.svg"],
  ["https://cooltext.com/", "image/others.svg"],
  ["https://illustrationkit.com/", "image/others.svg"],
  ["https://doodad.dev/pattern-generator/", "image/others.svg"],
  ["https://pattern.monster/", "image/others.svg"],
  [
    "https://themeselection.com/products/exemplar-free-avatar-library-for-figma-and-sketch/",
    "image/others.svg",
  ],
  ["https://uibundle.com", "image/others.svg"],
  ["http://openby.design/", "image/others.svg"],
  ["https://designstripe.com/catalog", "image/others.svg"],
  ["https://holasvg.com/", "image/others.svg"],
  ["https://symu.co/freebies/templates-4/", "image/others.svg"],
  ["https://meshgradient.in/", "image/others.svg"],
  ["https://alvarotrigo.com/shadow-gradients/", "image/others.svg"],
  ["https://boringavatars.com/", "image/others.svg"],
  [
    "https://www.figma.com/community/plugin/1159123024924461424/html.to.design",
    "image/figma.svg",
  ],
  ["https://fonts.google.com/", "image/others.svg"],
  ["https://www.dafont.com/", "image/others.svg"],
  ["https://usemodify.com/", "image/others.svg"],
  ["https://www.1001freefonts.com/", "image/others.svg"],
  ["https://www.fontsquirrel.com/", "image/others.svg"],
  ["https://www.fontfabric.com/free-fonts/", "image/others.svg"],
  ["https://tiff.herokuapp.com/", "image/others.svg"],
  ["https://practice.typekit.com/", "image/others.svg"],
  ["https://fontjoy.com/", "image/others.svg"],
  ["https://grtcalculator.com/", "image/others.svg"],
  ["https://www.fontget.com/", "image/others.svg"],
  ["https://fontpair.co/", "image/others.svg"],
  ["https://www.fontspace.com/", "image/others.svg"],
  ["http://www.abstractfonts.com/", "image/others.svg"],
  ["https://freetypography.com/", "image/others.svg"],
  ["https://github.com/cmiscm/leonsans/", "image/others.svg"],
  ["https://www.lexend.com/", "image/others.svg"],
  ["https://developer.apple.com/fonts/", "image/others.svg"],
  ["https://github.com/blaisck/sfwin/", "image/others.svg"],
  ["https://fontflipper.com/", "image/others.svg"],
  ["https://fontsarena.com/", "image/others.svg"],
  ["https://befonts.com/", "image/others.svg"],
  ["https://arabicfonts.net/", "image/others.svg"],
  ["https://fontdrop.info", "image/others.svg"],
  ["https://open-foundry.com", "image/others.svg"],
  ["https://glyphter.com", "image/others.svg"],
  ["https://google-webfonts-helper.herokuapp.com/fonts", "image/others.svg"],
  ["https://djamshed.github.io/rough-awesome-font/dist/", "image/others.svg"],
  ["https://ffonts.net", "image/others.svg"],
  ["https://smc.org.in/fonts/", "image/others.svg"],
  ["https://devfonts.gafi.dev/", "image/others.svg"],
  ["https://fontm.com/", "image/others.svg"],
  ["https://www.wfonts.com/", "image/others.svg"],
  ["https://modern-fluid-typography.vercel.app/", "image/others.svg"],
  ["https://www.urbanfonts.com/", "image/others.svg"],
  ["https://typespiration.com/", "image/others.svg"],
  ["https://fontsource.org/", "image/others.svg"],
  ["https://www.fontbolt.com/", "image/others.svg"],
  ["https://colorbrewer2.org/", "image/others.svg"],
  ["https://github.com/ardov/huetone", "image/others.svg"],
  ["http://colormind.io", "image/others.svg"],
  ["https://colorcurves.app", "image/others.svg"],
  ["https://colorgradient.dev/", "image/others.svg"],
  ["https://coolors.co", "image/others.svg"],
  ["https://htmlcolorcodes.com/", "image/others.svg"],
  ["https://www.colorsandfonts.com/", "image/others.svg"],
  ["https://www.palettelist.com/", "image/others.svg"],
  ["https://material.io/resources/color/", "image/others.svg"],
  ["https://www.materialpalette.com/", "image/others.svg"],
  ["https://mycolor.space/", "image/others.svg"],
  ["https://flatuicolors.com", "image/others.svg"],
  ["https://color.adobe.com/create", "image/others.svg"],
  ["https://colorsinspo.com/", "image/others.svg"],
  ["https://colorswall.com/", "image/others.svg"],
  ["https://www.happyhues.co/", "image/others.svg"],
  ["https://color.adobe.com/trends", "image/others.svg"],
  ["https://colorhunt.co/", "image/others.svg"],
  ["https://gradienthunt.com/", "image/others.svg"],
  ["https://webgradients.com/", "image/others.svg"],
  ["https://www.colorbox.io", "image/others.svg"],
  ["https://cssgradient.io/", "image/others.svg"],
  ["https://gradienta.io/", "image/others.svg"],
  ["https://uigradients.com/", "image/others.svg"],
  ["https://palettegenerator.colorion.co/", "image/others.svg"],
  ["https://material.colorion.co/", "image/others.svg"],
  ["https://www.grabient.com/", "image/others.svg"],
  ["https://shadeswash.netlify.app/", "image/others.svg"],
  ["http://brandcolors.net/", "image/others.svg"],
  ["https://brandpalettes.com/", "image/others.svg"],
  ["http://mcg.mbitson.com", "image/others.svg"],
  ["https://colorate.azurewebsites.net/", "image/others.svg"],
  ["https://www.0to255.com/", "image/others.svg"],
  ["https://meyerweb.com/eric/tools/color-blend", "image/others.svg"],
  ["https://gradientbuttons.colorion.co/", "image/others.svg"],
  ["http://khroma.co/", "image/others.svg"],
  ["https://whocanuse.com", "image/others.svg"],
  ["https://colorable.jxnblk.com/", "image/others.svg"],
  ["https://colorhexpicker.com", "image/others.svg"],
  ["https://saruwakakun.com/en/color-ideas", "image/others.svg"],
  ["https://paletton.com/", "image/others.svg"],
  ["https://www.colorzilla.com/", "image/others.svg"],
  ["https://www.cssgradienteditor.com", "image/others.svg"],
  ["https://image-color.com/", "image/others.svg"],
  ["https://combinecolors.com/", "image/others.svg"],
  ["https://www.colourlovers.com/palettes", "image/others.svg"],
  ["https://www.htmlcsscolor.com/", "image/others.svg"],
  ["https://hexcolorcodes.org/", "image/others.svg"],
  ["https://webkul.github.io/coolhue/", "image/others.svg"],
  ["https://colors.lol/", "image/others.svg"],
  ["https://colors.dopely.top/", "image/others.svg"],
  ["https://uicolorpicker.com/", "image/others.svg"],
  ["https://www.color-hex.com", "image/others.svg"],
  ["https://farbvelo.elastiq.ch/", "image/others.svg"],
  ["https://verandacolor.com", "image/others.svg"],
  ["https://duo.alexpate.uk/", "image/others.svg"],
  ["https://lospec.com/palette-list", "image/others.svg"],
  ["https://palettte.app", "image/others.svg"],
  ["https://www.eggradients.com/", "image/others.svg"],
  ["https://www.gradientos.app/", "image/others.svg"],
  ["https://encycolorpedia.com/", "image/others.svg"],
  ["https://croma.app/", "image/others.svg"],
  ["https://colordesigner.io/gradient-generator", "image/others.svg"],
  ["https://duotone.shapefactory.co/", "image/others.svg"],
  ["https://coolbackgrounds.io/", "image/others.svg"],
  ["https://mdigi.tools/color-shades/", "image/others.svg"],
  ["https://circumicons.com/", "image/others.svg"],
  ["https://uxwing.com/", "image/others.svg"],
  ["https://shapedfonts.com/iconclub/", "image/others.svg"],
  ["https://feathericons.com/", "image/others.svg"],
  ["https://tablericons.com/", "image/others.svg"],
  ["https://www.xicons.org/#/", "image/others.svg"],
  ["https://iconoir.com/", "image/others.svg"],
  ["https://simpleicons.org/", "image/others.svg"],
  ["https://linearicons.com/free", "image/others.svg"],
  ["https://icons8.com/", "image/others.svg"],
  ["https://www.flaticon.com/", "image/others.svg"],
  ["https://thenounproject.com/", "image/others.svg"],
  ["https://iconscout.com/", "image/others.svg"],
  ["https://iconsear.ch/search.html", "image/others.svg"],
  ["https://nucleoapp.com/", "image/others.svg"],
  ["https://icon-icons.com/", "image/others.svg"],
  ["https://icons.getbootstrap.com/", "image/others.svg"],
  ["https://remixicon.com/", "image/others.svg"],
  ["https://iconmonstr.com/", "image/others.svg"],
  ["https://webkul.github.io/vivid/", "image/others.svg"],
  ["https://www.iconfinder.com/", "image/others.svg"],
  ["https://lordicon.com/icons#free", "image/others.svg"],
  ["https://useanimations.com/", "image/others.svg"],
  ["https://css.gg/", "image/others.svg"],
  ["https://www.iconbros.com", "image/others.svg"],
  ["https://materialdesignicons.com/", "image/others.svg"],
  ["https://heroicons.dev/", "image/others.svg"],
  ["https://www.zondicons.com/icons.html", "image/others.svg"],
  ["http://endlessicons.com/", "image/others.svg"],
  ["https://icomoon.io/app/", "image/others.svg"],
  ["https://akveo.github.io/eva-icons/#/", "image/others.svg"],
  ["http://cryptoicons.co/", "image/others.svg"],
  ["https://ikonate.com/", "image/others.svg"],
  ["https://appicon.co/", "image/others.svg"],
  ["https://lineicons.com", "image/others.svg"],
  [
    "https://www.figma.com/resources/assets/evericons-for-figma/",
    "image/figma.svg",
  ],
  ["https://www.svgrepo.com/", "image/others.svg"],
  ["https://convertio.co/png-svg/", "image/others.svg"],
  ["https://cssicon.space/", "image/others.svg"],
  ["https://iconify.design/", "image/others.svg"],
  ["https://systemuicons.com/", "image/others.svg"],
  ["https://github.com/bytedance/IconPark", "image/others.svg"],
  ["https://icons.modulz.app/", "image/others.svg"],
  ["https://icons.eosdesignsystem.com/", "image/others.svg"],
  ["https://ionicons.com", "image/others.svg"],
  ["https://phosphoricons.com", "image/others.svg"],
  ["https://teenyicons.com/", "image/others.svg"],
  ["https://lucide.netlify.app/", "image/others.svg"],
  ["https://icones.js.org/", "image/others.svg"],
  ["https://shittyicons.com/", "image/others.svg"],
  ["https://www.iconspedia.com/", "image/others.svg"],
  ["https://iconhub.io/", "image/others.svg"],
  ["https://3dicons.co", "image/others.svg"],
  ["https://www.iconsdb.com/", "image/others.svg"],
  ["https://emojiguide.org/", "image/others.svg"],
  ["http://instantlogosearch.com/", "image/others.svg"],
  ["https://logosear.ch/search.html", "image/others.svg"],
  ["https://svgporn.com", "image/others.svg"],
  ["https://github.com/mpay24/payment-logos/", "image/others.svg"],
  ["https://github.com/alrra/browser-logos/", "image/others.svg"],
  ["https://www.vectorlogo.zone/", "image/others.svg"],
  ["https://worldvectorlogo.com/", "image/others.svg"],
  ["https://logomakr.com/", "image/others.svg"],
  ["https://www.namecheap.com/logo-maker/", "image/others.svg"],
  ["https://www.logo.wine/", "image/others.svg"],
  ["https://favicon.io/", "image/others.svg"],
  ["https://favicomatic.com/", "image/others.svg"],
  ["http://tools.dynamicdrive.com/favicon/", "image/others.svg"],
  ["https://realfavicongenerator.net/", "image/others.svg"],
  ["https://gauger.io/fonticon/", "image/others.svg"],
  ["https://www.favicon.cc", "image/others.svg"],
  ["https://maskable.app/editor/", "image/others.svg"],
  ["https://fontawesome.com/", "image/others.svg"],
  ["https://icons8.com/line-awesome", "image/others.svg"],
  ["https://material.io/resources/icons/", "image/others.svg"],
  ["http://ionicons.com/", "image/others.svg"],
  ["https://zurb.com/playground/foundation-icon-fonts-3", "image/others.svg"],
  ["https://fontisto.com/", "image/others.svg"],
  ["https://boxicons.com/", "image/others.svg"],
  ["https://icofont.com/", "image/others.svg"],
  ["https://www.materialpalette.com/icons", "image/others.svg"],
  [
    "http://zavoloklom.github.io/material-design-iconic-font/index.html",
    "image/others.svg",
  ],
  [
    "https://microsoft.github.io/vscode-codicons/dist/codicon.html",
    "image/others.svg",
  ],
  ["https://devicon.dev", "image/others.svg"],
  ["https://github.com/AlexanderPoellmann/PaymentFont", "image/others.svg"],
  ["https://erikflowers.github.io/weather-icons/", "image/others.svg"],
  [
    "https://themes-pixeden.com/font-demos/7-stroke/index.html",
    "image/others.svg",
  ],
  ["https://jam-icons.com/", "image/others.svg"],
  ["http://fontello.com/", "image/others.svg"],
  ["https://linea.io/", "image/others.svg"],
  ["https://iconscout.com/unicons", "image/others.svg"],
  ["https://mobiriseicons.com/", "image/others.svg"],
  ["https://www.pexels.com/", "image/others.svg"],
  ["https://unsplash.com/", "image/others.svg"],
  ["https://pixabay.com/", "image/others.svg"],
  ["https://magdeleine.co/", "image/others.svg"],
  ["https://picspree.com", "image/others.svg"],
  ["https://burst.shopify.com/", "image/others.svg"],
  ["https://gratisography.com/", "image/others.svg"],
  ["https://www.lifeofpix.com/", "image/others.svg"],
  ["https://stocksnap.io/", "image/others.svg"],
  ["https://morguefile.com/", "image/others.svg"],
  ["https://kaboompics.com/", "image/others.svg"],
  ["https://nos.twnsnd.co/", "image/others.svg"],
  ["https://picjumbo.com/", "image/others.svg"],
  ["https://www.publicdomainpictures.net/en/", "image/others.svg"],
  ["https://www.chamberofcommerce.org/findaphoto/", "image/others.svg"],
  ["http://www.stockvault.net/", "image/others.svg"],
  ["https://placeholder.com/", "image/others.svg"],
  ["https://realisticshots.com/", "image/others.svg"],
  ["https://negativespace.co/", "image/others.svg"],
  ["https://skitterphoto.com/", "image/others.svg"],
  ["https://picography.co/", "image/others.svg"],
  ["https://wunderstock.com/", "image/others.svg"],
  ["https://pxhere.com/", "image/others.svg"],
  ["https://piqsels.com/", "image/others.svg"],
  ["https://www.foodiesfeed.com/", "image/others.svg"],
  ["https://www.nappy.co/", "image/others.svg"],
  ["https://generated.photos/", "image/others.svg"],
  ["https://www.reshot.com/", "image/others.svg"],
  ["https://www.freeimages.com/", "image/others.svg"],
  ["https://picsum.photos/", "image/others.svg"],
  ["https://www.scienceimage.csiro.au", "image/others.svg"],
  ["https://ian.umces.edu/imagelibrary", "image/others.svg"],
  ["http://www.freenatureimages.eu", "image/others.svg"],
  ["https://search.creativecommons.org", "image/others.svg"],
  ["https://allthefreestock.com/", "image/others.svg"],
  ["https://lorem.space", "image/others.svg"],
  ["https://wordpress.org/openverse/", "image/others.svg"],
  ["https://www.pexels.com/videos", "image/others.svg"],
  ["https://www.pixabay.com/videos", "image/others.svg"],
  ["https://coverr.co/", "image/others.svg"],
  ["https://www.videezy.com/", "image/others.svg"],
  ["https://mixkit.co/", "image/others.svg"],
  ["https://www.lifeofvids.com/", "image/others.svg"],
  ["https://www.videvo.net/stock-video-footage/", "image/others.svg"],
  ["http://stock.loopvidz.com/", "image/others.svg"],
  ["https://www.splitshire.com/", "image/others.svg"],
  ["https://free-stock.video", "image/others.svg"],
  ["https://www.youtube.com/audiolibrary", "image/others.svg"],
  ["https://www.free-stock-music.com/", "image/others.svg"],
  ["https://www.bensound.com/", "image/others.svg"],
  ["https://mixkit.co/free-stock-music/", "image/others.svg"],
  ["https://freesound.org/", "image/others.svg"],
  ["https://freemusicarchive.org/", "image/others.svg"],
  ["https://musopen.org/music/", "image/others.svg"],
  ["https://pixabay.com/music/", "image/others.svg"],
  ["https://www.unminus.com/", "image/others.svg"],
  ["https://www.vecteezy.com/", "image/others.svg"],
  ["https://www.freepik.com", "image/others.svg"],
  ["https://www.freevectors.net/", "image/others.svg"],
  ["https://pngtree.com/free-vectors", "image/others.svg"],
  ["https://www.vector4free.com/", "image/others.svg"],
  ["http://freebbble.com/", "image/others.svg"],
  ["https://lukaszadam.com/", "image/others.svg"],
  ["https://illlustrations.co/", "image/others.svg"],
  ["https://www.clipart.email/", "image/others.svg"],
  ["https://growwwkit.com/illustrations/phonies", "image/others.svg"],
  ["https://trianglify.io/", "image/others.svg"],
  ["https://blobs.app/", "image/others.svg"],
  ["https://www.hiclipart.com/", "image/others.svg"],
  ["https://stories.freepik.com/", "image/others.svg"],
  ["https://www.blackillustrations.com/", "image/others.svg"],
  ["https://delesign.com/free-designs/graphics", "image/others.svg"],
  ["https://www.shapedivider.app/", "image/others.svg"],
  ["https://smart.servier.com", "image/others.svg"],
  ["http://www.clker.com", "image/others.svg"],
  ["https://svgwave.in/", "image/others.svg"],
  ["https://bgjar.com", "image/others.svg"],
  [
    "https://www.heritagetype.com/collections/free-vintage-illustrations",
    "image/others.svg",
  ],
  ["https://robohash.org/", "image/others.svg"],
  ["https://tabbied.com/", "image/others.svg"],
  ["https://app.haikei.app/", "image/others.svg"],
  ["https://vector.ma/", "image/others.svg"],
  ["https://app.heazy.studio/", "image/others.svg"],
  ["https://smartmockups.com/", "image/others.svg"],
  ["https://mediamodifier.com/", "image/others.svg"],
  ["https://shotsnapp.com/", "image/others.svg"],
  ["https://www.screely.com/", "image/others.svg"],
  ["https://screenshot.rocks/", "image/others.svg"],
  ["https://screenpeek.io/", "image/others.svg"],
  ["https://www.mockupworld.co/", "image/others.svg"],
  ["https://www.collabshot.com/", "image/others.svg"],
  ["https://facebook.design/devices", "image/others.svg"],
  ["https://threed.io", "image/others.svg"],
  ["https://mockuphone.com/", "image/others.svg"],
  ["https://deviceshots.com/", "image/others.svg"],
  ["https://cleanmock.com/", "image/others.svg"],
  ["https://www.mock.video/", "image/others.svg"],
  ["https://mockupbro.com/", "image/others.svg"],
  ["https://animockup.com/", "image/others.svg"],
  ["https://pika.style", "image/others.svg"],
  ["https://html5up.net/", "image/others.svg"],
  ["https://templatemo.com/", "image/others.svg"],
  ["https://freehtml5.co/", "image/others.svg"],
  ["https://www.styleshout.com/free-templates/", "image/others.svg"],
  ["https://startbootstrap.com/", "image/others.svg"],
  ["https://www.zerotheme.com/", "image/others.svg"],
  ["https://www.html5xcss3.com/", "image/others.svg"],
  ["https://colorlib.com/wp/templates/", "image/others.svg"],
  ["https://www.free-css.com/free-css-templates", "image/others.svg"],
  ["https://www.hubspot.com/resources", "image/others.svg"],
  ["https://mobirise.com/html-templates/", "image/others.svg"],
  ["https://bootswatch.com/", "image/others.svg"],
  ["https://onepagelove.com/", "image/others.svg"],
  ["https://themesfor.app/", "image/others.svg"],
  ["https://bootstraptaste.com/", "image/others.svg"],
  ["https://bootstrapmade.com/", "image/others.svg"],
  ["https://w3layouts.com/", "image/others.svg"],
  ["https://www.tooplate.com/", "image/others.svg"],
  ["https://cruip.com/free-templates/", "image/others.svg"],
  ["https://uideck.com/", "image/others.svg"],
  ["https://splawr.com/", "image/others.svg"],
  ["https://www.w3schools.com/w3css/w3css_templates.asp", "image/others.svg"],
  [
    "https://all-free-download.com/free-website-templates/free-html-css-templates.html",
    "image/others.svg",
  ],
  ["http://www.mashup-template.com/templates.html", "image/others.svg"],
  [
    "https://github.com/themeselection/sneat-html-admin-template-free",
    "image/others.svg",
  ],
  ["https://tailwindcss.com/", "image/tailwindcss.svg"],
  ["https://getbootstrap.com/", "image/others.svg"],
  ["https://materializecss.com/", "image/others.svg"],
  ["https://getmdl.io/", "image/others.svg"],
  ["https://bulma.io/", "image/others.svg"],
  ["http://getskeleton.com/", "image/others.svg"],
  ["https://uniformcss.com/", "image/others.svg"],
  ["https://semantic-ui.com/", "image/others.svg"],
  ["https://fomantic-ui.com/", "image/others.svg"],
  ["https://get.foundation/", "image/others.svg"],
  ["https://purecss.io/", "image/others.svg"],
  ["https://getuikit.com/", "image/others.svg"],
  ["https://www.oddbird.net/susy/", "image/others.svg"],
  ["https://milligram.io/", "image/others.svg"],
  ["https://vanillaframework.io/", "image/others.svg"],
  ["https://picturepan2.github.io/spectre/", "image/others.svg"],
  ["https://picnicss.com/", "image/others.svg"],
  ["https://kbrsh.github.io/wing/", "image/others.svg"],
  ["https://jenil.github.io/chota/", "image/others.svg"],
  ["https://blueprintcss.dev/", "image/others.svg"],
  ["https://www.w3schools.com/w3css/", "image/others.svg"],
  ["https://jdan.github.io/98.css/", "image/others.svg"],
  ["https://nostalgic-css.github.io/NES.css/", "image/others.svg"],
  ["https://www.shoelace.style/", "image/others.svg"],
  ["https://andybrewer.github.io/mvp/", "image/others.svg"],
  ["http://blazecss.com/", "image/others.svg"],
  ["https://turretcss.com/", "image/others.svg"],
  ["https://www.cutestrap.com/", "image/others.svg"],
  ["https://botoxparty.github.io/XP.css/", "image/others.svg"],
  ["https://framework7.io/", "image/others.svg"],
  ["https://kushagra.dev/lab/hint/", "image/others.svg"],
  ["http://imagehover.io/", "image/others.svg"],
  ["https://minicss.org/", "image/others.svg"],
  ["https://tachyons.io/", "image/others.svg"],
  [
    "https://fezvrasta.github.io/bootstrap-material-design/",
    "image/others.svg",
  ],
  ["https://github.com/IVORY-UI/ivory", "image/others.svg"],
  ["https://www.gethalfmoon.com/", "image/others.svg"],
  ["https://metroui.org.ua/index.html", "image/others.svg"],
  ["https://css-doodle.com/", "image/others.svg"],
  ["https://latex.now.sh/", "image/others.svg"],
  ["https://github.com/cognitom/paper-css", "image/others.svg"],
  ["https://windicss.org/", "image/others.svg"],
  ["https://cirrus-ui.netlify.app/", "image/others.svg"],
  ["https://github.com/BafS/Gutenberg", "image/others.svg"],
  ["https://github.com/ajusa/lit", "image/others.svg"],
  ["https://github.com/arwes/arwes", "image/others.svg"],
  ["https://bojler.slicejack.com/", "image/others.svg"],
  ["https://github.com/yegor256/tacit", "image/others.svg"],
  ["https://terminalcss.xyz/", "image/others.svg"],
  ["https://oxal.org/projects/sakura/", "image/others.svg"],
  ["https://github.com/micah5/PSone.css", "image/others.svg"],
  ["https://github.com/mblode/marx", "image/others.svg"],
  ["https://github.com/edwardtufte/tufte-css", "image/others.svg"],
  ["https://useaxentix.com/", "image/others.svg"],
  ["https://rsms.me/raster/", "image/others.svg"],
  ["https://flowrift.com/c/banner", "image/others.svg"],
  ["https://twind.dev/", "image/others.svg"],
  ["https://picocss.com/", "image/others.svg"],
  ["https://github.com/codeAdrian/clay.css", "image/others.svg"],
  ["http://oocss.org/", "image/others.svg"],
  ["https://acss.io/", "image/others.svg"],
  ["http://getbem.com/", "image/others.svg"],
  ["http://smacss.com/", "image/others.svg"],
  ["https://animate.style/", "image/others.svg"],
  ["http://bouncejs.com/", "image/others.svg"],
  ["https://animejs.com/", "image/others.svg"],
  ["https://www.minimamente.com/project/magic/", "image/others.svg"],
  ["https://zzz.dog/", "image/others.svg"],
  ["http://elrumordelaluz.github.io/csshake/", "image/others.svg"],
  ["http://ianlunn.github.io/Hover/", "image/others.svg"],
  ["http://anijs.github.io/", "image/others.svg"],
  ["http://animista.net/", "image/others.svg"],
  ["https://github.com/anater/tachyons-animate", "image/others.svg"],
  ["https://www.sequencejs.com/", "image/others.svg"],
  ["https://tilomitra.github.io/infinite/", "image/others.svg"],
  ["http://tholman.com/obnoxious/", "image/others.svg"],
  ["https://zurb.com/playground/motion-ui", "image/others.svg"],
  ["https://keyframes.app/", "image/others.svg"],
  [
    "https://thoughtbot.com/blog/transitions-and-transforms",
    "image/others.svg",
  ],
  ["https://svgartista.net/", "image/others.svg"],
  ["https://animxyz.com/", "image/others.svg"],
  ["https://github.com/jh3y/whirl", "image/others.svg"],
  ["https://jonsuh.com/hamburgers/", "image/others.svg"],
  ["https://cssloaders.github.io/", "image/others.svg"],
  ["https://motion.dev/", "image/others.svg"],
  ["https://pocoloco.io/", "image/others.svg"],
  ["https://drawcall.github.io/AniX/", "image/others.svg"],
  ["https://michalsnik.github.io/aos/", "image/others.svg"],
  ["https://sarthology.github.io/Animatopy/", "image/others.svg"],
  ["https://greensock.com/", "image/others.svg"],
  ["http://velocityjs.org/", "image/others.svg"],
  ["https://github.com/alexfoxy/laxxx", "image/others.svg"],
  ["https://github.com/dixonandmoe/rellax", "image/others.svg"],
  ["https://github.com/mrdoob/three.js/", "image/others.svg"],
  ["https://atroposjs.com/", "image/others.svg"],
  ["https://wowjs.uk/", "image/others.svg"],
  ["http://chocolat.insipi.de/", "image/others.svg"],
  ["http://gijsroge.github.io/tilt.js/", "image/others.svg"],
  ["https://roughnotation.com/", "image/others.svg"],
  ["https://particles.js.org/", "image/others.svg"],
  ["https://vincentgarreau.com/particles.js/", "image/others.svg"],
  ["https://mojs.github.io/", "image/others.svg"],
  ["https://lokeshdhakar.com/projects/lightbox2/", "image/others.svg"],
  ["https://kenwheeler.github.io/slick/", "image/others.svg"],
  ["https://barba.js.org/", "image/others.svg"],
  ["https://locomotivemtl.github.io/locomotive-scroll/", "image/others.svg"],
  ["https://owlcarousel2.github.io/OwlCarousel2/", "image/others.svg"],
  ["https://swiperjs.com/", "image/others.svg"],
  ["https://splidejs.com", "image/others.svg"],
  ["https://simpleparallax.com/", "image/others.svg"],
  ["https://thednp.github.io/kute.js/", "image/others.svg"],
  ["https://sarcadass.github.io/granim.js/index.html", "image/others.svg"],
  ["https://popmotion.io/", "image/others.svg"],
  ["https://maxwellito.github.io/vivus/", "image/others.svg"],
  ["https://mattboldt.com/demos/typed-js/", "image/others.svg"],
  ["https://kimmobrunfeldt.github.io/progressbar.js/", "image/others.svg"],
  ["https://aerolab.github.io/midnight.js/", "image/others.svg"],
  ["https://tingle.robinparisi.com/", "image/others.svg"],
  ["https://www.theatrejs.com/", "image/others.svg"],
  ["https://splidejs.com/", "image/others.svg"],
  ["https://gvguy.github.io/nice-waves/", "image/others.svg"],
  ["https://www.vantajs.com/", "image/others.svg"],
  ["https://splitting.js.org/", "image/others.svg"],
  ["https://www.chartjs.org/", "image/others.svg"],
  ["https://frappe.io/charts", "image/others.svg"],
  ["https://g2plot.antv.vision/en", "image/others.svg"],
  ["https://developers.google.com/chart/", "image/others.svg"],
  ["https://d3js.org/", "image/others.svg"],
  ["https://apexcharts.com/", "image/others.svg"],
  ["http://gionkunz.github.io/chartist-js/index.html", "image/others.svg"],
  ["https://lib.vizzuhq.com/0.3.0/", "image/others.svg"],
  ["https://charts.ant.design/en", "image/others.svg"],
  ["https://bit.dev/components", "image/others.svg"],
  ["http://uilang.com/", "image/others.svg"],
  ["https://medialoot.com/free-themes/css-components/", "image/others.svg"],
  ["https://froala.com/design-blocks", "image/others.svg"],
  ["https://flowbite.com", "image/others.svg"],
  ["https://daisyui.com/", "image/others.svg"],
  ["https://mui-treasury.com", "image/others.svg"],
  ["https://mdbootstrap.com/", "image/others.svg"],
  ["http://photonkit.com/", "image/others.svg"],
  ["https://designmodo.github.io/Flat-UI/", "image/others.svg"],
  ["https://designrevision.com/downloads/shards/", "image/others.svg"],
  ["https://themesberg.com/templates/free", "image/others.svg"],
  ["https://www.creative-tim.com/", "image/others.svg"],
  ["https://brumm.af/shadows", "image/others.svg"],
  ["https://adminlte.io/", "image/others.svg"],
  ["https://tobiasahlin.com/spinkit/", "image/others.svg"],
  ["https://epic-spinners.epicmax.co/", "image/others.svg"],
  ["https://loading.io/", "image/others.svg"],
  ["https://tobiasahlin.com/moving-letters/", "image/others.svg"],
  ["https://csslayout.io/", "image/others.svg"],
  ["https://cssgrid-generator.netlify.app/", "image/others.svg"],
  ["https://codyhouse.co/", "image/others.svg"],
  [
    "https://github.com/creativetimofficial/tailwind-starter-kit",
    "image/others.svg",
  ],
  ["https://www.tailwindtoolbox.com/", "image/others.svg"],
  ["https://tailwindcomponents.com/", "image/others.svg"],
  ["https://sweetalert.js.org/", "image/others.svg"],
  ["https://sweetalert2.github.io/", "image/others.svg"],
  ["https://mertjf.github.io/tailblocks/", "image/others.svg"],
  ["https://soft-components-docs.web.app/", "image/others.svg"],
  ["https://www.fast.design/", "image/others.svg"],
  ["https://lottiefiles.com/", "image/others.svg"],
  ["https://kutty.netlify.app/", "image/others.svg"],
  ["https://tailwindtemplates.io/", "image/others.svg"],
  ["https://stitches.hyperyolo.com/", "image/others.svg"],
  ["https://merakiui.com/", "image/others.svg"],
  ["https://http://daemonite.github.io/material/", "image/others.svg"],
  ["https://stitches.dev/", "image/others.svg"],
  ["https://headlessui.dev/", "image/others.svg"],
  ["https://styled-components.com/", "image/others.svg"],
  [
    "https://drive.google.com/file/d/1SZOTxXYfCMujqP2P684Vd5QIrlk5bwe6/view?usp=sharing",
    "image/others.svg",
  ],
  ["https://notiflix.github.io", "image/others.svg"],
  ["https://coreui.io", "image/others.svg"],
  ["https://www.agnosticui.com/", "image/others.svg"],
  ["https://react-svgr.com/", "image/others.svg"],
  ["https://uiverse.io", "image/others.svg"],
  ["https://www.hyperui.dev/", "image/others.svg"],
  [
    "https://github.com/themesberg/flowbite-admin-dashboard",
    "image/others.svg",
  ],
  ["https://material-ui.com/", "image/others.svg"],
  ["https://chakra-ui.com/", "image/others.svg"],
  ["https://react-bootstrap.github.io/", "image/bootstrap.svg"],
  ["https://semi.design/en-US", "image/others.svg"],
  ["https://mantine.dev/", "image/others.svg"],
  ["https://nextui.org/", "image/others.svg"],
  ["https://arco.design/en-US", "image/others.svg"],
  ["https://uiplaybook.dev/", "image/others.svg"],
  ["https://reactstrap.github.io/", "image/others.svg"],
  ["https://marmelab.com/react-admin/", "image/others.svg"],
  ["https://blueprintjs.com/", "image/others.svg"],
  ["https://react.semantic-ui.com/", "image/react.svg"],
  ["https://designrevision.com/downloads/shards-react/", "image/others.svg"],
  ["https://bvaughn.github.io/react-virtualized", "image/others.svg"],
  ["http://react-toolbox.io/#/", "image/others.svg"],
  ["https://elastic.github.io/eui/#/", "image/others.svg"],
  ["http://reactdesktop.js.org/", "image/others.svg"],
  ["https://theme-ui.com/home", "image/others.svg"],
  ["https://onsen.io/react/", "image/others.svg"],
  ["https://evergreen.segment.com/", "image/others.svg"],
  ["https://rebassjs.org/", "image/others.svg"],
  ["https://v2.grommet.io/", "image/others.svg"],
  ["https://github.com/cruip/open-react-template/", "image/others.svg"],
  ["http://elemental-ui.com/", "image/others.svg"],
  ["https://ant.design/", "image/others.svg"],
  ["https://bumbag.style/", "image/others.svg"],
  ["https://www.primefaces.org/primereact/", "image/others.svg"],
  ["https://primer.style/components/", "image/others.svg"],
  ["https://orbit.kiwi/", "image/others.svg"],
  ["https://baseweb.design/", "image/others.svg"],
  [
    "http://lonelyplanet.github.io/backpack-ui/?path=/story/styles--design-tokens",
    "image/others.svg",
  ],
  ["https://reaviz.io", "image/others.svg"],
  ["https://rsuitejs.com/en/", "image/others.svg"],
  ["https://www.react-spring.io/", "image/others.svg"],
  ["http://recharts.org/en-US/", "image/others.svg"],
  ["https://github.com/geist-org/react", "image/others.svg"],
  ["https://www.framer.com/motion/", "image/others.svg"],
  [
    "https://react-spectrum.adobe.com/react-spectrum/index.html",
    "image/others.svg",
  ],
  [
    "https://github.com/matteobruni/tsparticles/tree/main/components/react",
    "image/others.svg",
  ],
  ["https://github.com/lindelof/particles-bg", "image/others.svg"],
  ["https://treact.owaiskhan.me", "image/others.svg"],
  [
    "https://gatsby-admin.paljs.com/extra-components/progress/",
    "image/others.svg",
  ],
  [
    "https://demo.uifort.com/carolina-react-admin-dashboard-material-ui-free-demo/LandingPage",
    "image/others.svg",
  ],
  ["https://github.com/tabler/tabler-react", "image/others.svg"],
  ["https://github.com/sha-el/sha-el-design", "image/others.svg"],
  [
    "https://weui.github.io/react-weui/docs/#/react-weui/docs/page/0/articles/0",
    "image/others.svg",
  ],
  ["https://ui.supabase.io/", "image/others.svg"],
  ["https://github.com/JetBrains/ring-ui", "image/others.svg"],
  ["https://react95.io/", "image/others.svg"],
  ["https://reakit.io/", "image/others.svg"],
  ["https://github.com/youzan/zent", "image/others.svg"],
  ["https://github.com/pinterest/gestalt", "image/others.svg"],
  ["https://xstyled.dev/", "image/others.svg"],
  ["https://github.com/pmndrs/use-gesture", "image/others.svg"],
  ["https://react-rainbow.io/", "image/others.svg"],
  [
    "https://github.com/saidMounaim/React-Use-Smooth-Scroll",
    "image/others.svg",
  ],
  ["https://choc-ui.com/", "image/others.svg"],
  ["https://elementz.style/", "image/others.svg"],
  ["https://www.radix-ui.com/", "image/others.svg"],
  [
    "https://github.com/themeselection/materio-mui-react-nextjs-admin-template-free",
    "image/others.svg",
  ],
  ["https://chakra-templates.dev/", "image/others.svg"],
  ["https://github.com/bvaughn/react-resizable-panels", "image/others.svg"],
  [
    "https://carbondesignsystem.com/developing/frameworks/react/",
    "image/others.svg",
  ],
  ["https://vuetifyjs.com/en/", "image/others.svg"],
  ["https://bootstrap-vue.org/", "image/bootstrap.svg"],
  ["https://buefy.org/", "image/others.svg"],
  ["https://semantic-ui-vue.github.io", "image/others.svg"],
  ["https://arco.design/vue/en-US/docs/start", "image/others.svg"],
  ["https://veui.dev/en-US", "image/others.svg"],
  ["https://github.com/Trendyol/grace", "image/others.svg"],
  ["https://quasar.dev/", "image/others.svg"],
  ["https://element.eleme.io/#/en-US", "image/others.svg"],
  ["https://myliang.github.io/fish-ui/#/components/index", "image/others.svg"],
  ["https://josephuspaye.github.io/Keen-UI", "image/others.svg"],
  [
    "https://github.com/themeselection/materio-vuetify-vuejs-admin-template-free",
    "image/others.svg",
  ],
  ["https://onsen.io/vue/", "image/others.svg"],
  ["https://vuejsexamples.com", "image/others.svg"],
  ["https://inkline.io", "image/others.svg"],
  ["https://vuesax.com/", "image/others.svg"],
  ["https://antdv.com/", "image/others.svg"],
  ["https://designrevision.com/downloads/shards-vue/", "image/others.svg"],
  ["https://www.primefaces.org/primevue/", "image/others.svg"],
  ["https://vue.chakra-ui.com/", "image/others.svg"],
  ["https://www.iviewui.com/", "image/others.svg"],
  [
    "https://github.com/matteobruni/tsparticles/tree/main/components/vue",
    "image/others.svg",
  ],
  [
    "https://github.com/matteobruni/tsparticles/tree/main/components/vue3",
    "image/others.svg",
  ],
  ["https://components.timos.design", "image/others.svg"],
  ["https://youzan.github.io/vant", "image/others.svg"],
  ["https://quatrochan.github.io/Equal/", "image/others.svg"],
  ["https://mint-ui.github.io/#!/en", "image/others.svg"],
  ["https://didi.github.io/cube-ui/#/en-US", "image/others.svg"],
  ["https://muse-ui.org/#/en-US", "image/others.svg"],
  ["https://at-ui.github.io/at-ui/#/en", "image/others.svg"],
  ["https://vuikit.js.org/", "image/others.svg"],
  ["https://antoniandre.github.io/wave-ui/", "image/others.svg"],
  ["https://www.vue-tailwind.com/", "image/others.svg"],
  ["https://oruga.io/", "image/others.svg"],
  ["https://material.balmjs.com/#/", "image/others.svg"],
  ["https://github.com/apache/incubator-weex-ui", "image/others.svg"],
  ["https://github.com/haoziqaq/varlet", "image/others.svg"],
  ["https://www.naiveui.com/en-US/os-theme", "image/others.svg"],
  ["https://vuestic.dev/", "image/others.svg"],
  ["https://vue-final-modal.org/", "image/others.svg"],
  ["https://vuetensils.stegosource.com/", "image/others.svg"],
  ["https://material.angular.io/", "image/others.svg"],
  ["https://ng-bootstrap.github.io/#/home", "image/bootstrap.svg"],
  ["https://www.primefaces.org/primeng/#/", "image/others.svg"],
  ["https://onsen.io/angular2/", "image/others.svg"],
  ["https://ng-lightning.github.io/ng-lightning/#/", "image/others.svg"],
  ["https://ng-semantic.herokuapp.com/", "image/others.svg"],
  ["https://akveo.github.io/nebular/", "image/others.svg"],
  ["https://alyle.io/", "image/others.svg"],
  ["https://valor-software.com/ngx-bootstrap/#/", "image/others.svg"],
  ["https://ng.ant.design/", "image/others.svg"],
  ["https://www.npmjs.com/package/ngx-pagination", "image/others.svg"],
  ["https://www.npmjs.com/package/ng-multiselect-dropdown", "image/others.svg"],
  ["https://particles.matteobruni.it/", "image/others.svg"],
  ["https://teradata.github.io/covalent/v3/#/", "image/others.svg"],
  ["https://clarity.design/", "image/others.svg"],
  ["https://taiga-ui.dev/", "image/others.svg"],
  ["https://akveo.github.io/ngx-admin/", "image/others.svg"],
  ["https://sveltematerialui.com/", "image/others.svg"],
  ["https://bestguy.github.io/sveltestrap/", "image/others.svg"],
  ["https://svelteui.js.org/", "image/others.svg"],
  [
    "https://github.com/matteobruni/tsparticles/tree/main/components/svelte",
    "image/others.svg",
  ],
  ["https://illright.github.io/attractions/", "image/others.svg"],
  ["https://docs.svelteit.dev", "image/others.svg"],
  ["https://carbon-components-svelte.onrender.com/", "image/others.svg"],
  ["https://magnus-ui.com/", "image/others.svg"],
  ["https://wix.github.io/react-native-ui-lib/", "image/others.svg"],
  ["https://reactnativepaper.com/", "image/others.svg"],
  ["https://akveo.github.io/react-native-ui-kitten/", "image/others.svg"],
  ["https://reactnativeelements.com/", "image/others.svg"],
  ["https://nativebase.io/", "image/others.svg"],
  [
    "https://shoutem.github.io/docs/ui-toolkit/introduction",
    "image/others.svg",
  ],
  ["https://github.com/vadimdemedes/tailwind-rn", "image/others.svg"],
  ["https://rn.mobile.ant.design/", "image/others.svg"],
  ["https://github.com/snackui/snackui", "image/others.svg"],
  ["https://moti.fyi/", "image/others.svg"],
  ["https://tamagui.dev/", "image/others.svg"],
  ["https://material.io/", "image/others.svg"],
  ["https://developer.apple.com/design/resources/", "image/others.svg"],
  ["https://primer.style/", "image/others.svg"],
  [
    "https://www.oracle.com/webfolder/ux/middleware/alta/index.html",
    "image/others.svg",
  ],
  ["https://pulse.heartbeat.ua/", "image/others.svg"],
  ["https://boltdesignsystem.com/", "image/others.svg"],
  ["https://atlaskit.atlassian.com/", "image/others.svg"],
  [
    "https://www.audi.com/ci/en/guides/user-interface/introduction.html",
    "image/others.svg",
  ],
  ["https://www.carbondesignsystem.com/", "image/others.svg"],
  ["https://www.yelp.com/styleguide", "image/others.svg"],
  ["https://comet.discoveryeducation.com/", "image/others.svg"],
  ["https://etrade.design/", "image/others.svg"],
  ["https://sap.github.io/fundamental-styles/", "image/others.svg"],
  ["https://design.infor.com/", "image/others.svg"],
  ["https://liferay.design/lexicon/", "image/others.svg"],
  ["https://ux.mailchimp.com/patterns/color", "image/others.svg"],
  [
    "https://marvelapp.com/styleguide/overview/introduction",
    "image/others.svg",
  ],
  ["https://developer.microsoft.com/en-us/fluentui#/", "image/others.svg"],
  ["https://design-system.pluralsight.com/", "image/others.svg"],
  ["https://polaris.shopify.com/", "image/others.svg"],
  ["https://protocol.mozilla.org/", "image/others.svg"],
  ["http://styleguide.sendgrid.com/", "image/others.svg"],
  ["https://styleguide.vtex.com/", "image/others.svg"],
  [
    "https://rizzo.lonelyplanet.com/styleguide/design-elements",
    "image/others.svg",
  ],
  ["https://atomizecode.com/", "image/others.svg"],
  ["http://styleguides.io/", "image/others.svg"],
  ["https://uilibrary.github.io/done-design-system/", "image/others.svg"],
  ["https://skoda-brand.com/explore-our-brand", "image/others.svg"],
  ["https://spectrum.adobe.com/", "image/others.svg"],
  ["https://asphalt.gojek.io/", "image/others.svg"],
  ["https://lawsofux.com/", "image/others.svg"],
  ["https://www.checklist.design/", "image/others.svg"],
  ["https://humanebydesign.com/", "image/others.svg"],
  ["https://guidelines.pr1mer.tech", "image/others.svg"],
  ["https://www.patternfly.org/", "image/others.svg"],
  ["https://www.patterns.dev", "image/others.svg"],
  ["https://www.figma.com/graphic-design-tool/", "image/figma.svg"],
  ["https://penpot.app/", "image/others.svg"],
  ["https://vectr.com/", "image/others.svg"],
  ["https://www.taler.app/", "image/others.svg"],
  ["https://www.canva.com/", "image/others.svg"],
  ["https://getwaves.io/", "image/others.svg"],
  ["https://bennettfeely.com/clippy/", "image/others.svg"],
  [
    "https://9elements.github.io/fancy-border-radius/full-control.html",
    "image/others.svg",
  ],
  ["https://wireframe.cc/", "image/others.svg"],
  ["https://www.fotor.com/", "image/others.svg"],
  ["https://www.pixlr.com/", "image/others.svg"],
  ["https://animoto.com/apps/online-video-maker", "image/others.svg"],
  ["https://www.remove.bg/", "image/others.svg"],
  ["https://photos.icons8.com/creator", "image/others.svg"],
  ["https://www.visme.co/", "image/others.svg"],
  ["https://infogram.com/", "image/others.svg"],
  ["https://www.chartgo.com/", "image/others.svg"],
  ["https://cartoon.pho.to/", "image/others.svg"],
  ["https://whimsical.com/", "image/others.svg"],
  ["https://witeboard.com/", "image/others.svg"],
  ["https://octopus.do/", "image/others.svg"],
  ["https://onlineboard.eu", "image/others.svg"],
  ["https://www.clickminded.com/button-generator/", "image/others.svg"],
  ["https://www.blobmaker.app/", "image/others.svg"],
  ["https://personas.draftbit.com/", "image/others.svg"],
  ["https://www.photopea.com", "image/others.svg"],
  ["https://excalidraw.com/", "image/others.svg"],
  ["https://www.diagrams.net/", "image/others.svg"],
  ["https://github.com/mermaid-js/mermaid", "image/others.svg"],
  ["http://mapinseconds.com/", "image/others.svg"],
  ["http://grid.malven.co/", "image/others.svg"],
  ["http://flexbox.malven.co/", "image/others.svg"],
  ["https://icons8.com/upscaler", "image/others.svg"],
  ["https://getavataaars.com/", "image/others.svg"],
  ["https://github.com/RobertBroersma/bigheads", "image/others.svg"],
  ["https://webflow.com/", "image/others.svg"],
  ["https://stickermule.com/trace", "image/others.svg"],
  ["https://neumorphism.io/#55b9f3", "image/others.svg"],
  ["https://app.dbdesigner.net/", "image/others.svg"],
  ["https://uibakery.io/", "image/others.svg"],
  ["http://knutsynstad.com/fauxcode/", "image/others.svg"],
  ["https://rive.app/", "image/others.svg"],
  ["https://www.unscreen.com/", "image/others.svg"],
  ["https://www.kodeshot.net/", "image/others.svg"],
  ["https://www.wix.com/", "image/others.svg"],
  ["https://gtmetrix.com/", "image/others.svg"],
  ["https://yellowlab.tools/", "image/others.svg"],
  ["https://www.framer.com/", "image/others.svg"],
  ["https://www.draw.io/", "image/others.svg"],
  ["https://uxwing.com/svg-icon-editor", "image/others.svg"],
  ["http://www.cssarrowplease.com/", "image/others.svg"],
  ["https://www.lucidchart.com/pages/", "image/others.svg"],
  ["https://carbon.now.sh", "image/others.svg"],
  ["https://www.pixcleaner.com/", "image/others.svg"],
  ["https://ui.glass/generator", "image/others.svg"],
  ["https://glassmorphism.com/", "image/others.svg"],
  ["https://tableconvert.com/", "image/others.svg"],
  ["https://doodleipsum.com/", "image/others.svg"],
  ["https://figen.cc/", "image/others.svg"],
  ["https://www.devwares.com/windframe/", "image/others.svg"],
  ["https://slickr.vercel.app/", "image/others.svg"],
  ["https://www.joshwcomeau.com/shadow-palette/", "image/others.svg"],
  ["https://ray.so/", "image/others.svg"],
  ["https://www.codepng.app/", "image/others.svg"],
  ["https://grid.layoutit.com/", "image/others.svg"],
  ["https://www.jsont.run/", "image/others.svg"],
  ["https://jitter.video/", "image/others.svg"],
  ["https://www.visily.ai", "image/others.svg"],
  ["https://okso.app", "image/others.svg"],
  ["https://fpece.com/calc-generator", "image/others.svg"],
  ["https://www.gimp.org/", "image/others.svg"],
  ["https://www.designer.io/en/", "image/others.svg"],
  ["https://www.blender.org/download/", "image/others.svg"],
  ["https://rawtherapee.com/", "image/others.svg"],
  ["https://www.befunky.com/features/graphic-designer/", "image/others.svg"],
  ["https://krita.org/en/download/krita-desktop/", "image/others.svg"],
  ["https://pencil.evolus.vn/", "image/others.svg"],
  ["https://inkscape.org/", "image/others.svg"],
  ["https://www.adobe.com/products/xd.html", "image/others.svg"],
  ["https://shape.so/pricing", "image/others.svg"],
  ["https://icons8.com/lunacy", "image/others.svg"],
  ["https://www.invisionapp.com/studio", "image/others.svg"],
  ["https://www.darktable.org/", "image/others.svg"],
  ["https://www.inpixio.com/free-photo-editor", "image/others.svg"],
  ["https://colorpicker.fr", "image/others.svg"],
  ["https://webdesigner.withgoogle.com/", "image/others.svg"],
  ["https://origami.design", "image/others.svg"],
  ["http://csszengarden.com/", "image/others.svg"],
  ["https://www.behance.net/", "image/others.svg"],
  ["https://dribbble.com/", "image/others.svg"],
  ["https://landingfolio.com/", "image/others.svg"],
  ["https://www.codewell.cc/", "image/others.svg"],
  ["https://foxyapps.co/", "image/others.svg"],
  ["https://httpster.net/2020/apr/", "image/others.svg"],
  ["https://inspofinds.com/", "image/others.svg"],
  ["https://www.designnotes.co/", "image/others.svg"],
  ["https://land-book.com/", "image/others.svg"],
  ["https://www.frontendmentor.io/", "image/others.svg"],
  ["https://www.awwwards.com/", "image/others.svg"],
  ["https://tympanus.net/codrops/", "image/others.svg"],
  ["https://saaslandingpage.com/", "image/others.svg"],
  ["https://saaspages.xyz", "image/others.svg"],
  ["https://screenlane.com", "image/others.svg"],
  ["https://www.lapa.ninja/", "image/others.svg"],
  ["https://freefrontend.com/", "image/others.svg"],
  ["https://webframe.xyz", "image/others.svg"],
  ["http://collectui.com/", "image/others.svg"],
  ["https://graphicburger.com/", "image/others.svg"],
  ["https://reallygoodemails.com/", "image/others.svg"],
  ["https://freedesignresources.net/", "image/others.svg"],
  ["https://www.siteinspire.com/", "image/others.svg"],
  ["https://www.webdesign-inspiration.com/", "image/others.svg"],
  ["https://navnav.co/", "image/others.svg"],
  ["https://www.calltoidea.com/", "image/others.svg"],
  ["https://mediaqueri.es/", "image/others.svg"],
  ["https://search.muz.li", "image/others.svg"],
  ["https://www.deviantart.com/", "image/others.svg"],
  [
    "https://www.designyourway.net/blog/web-and-mobile-design/",
    "image/others.svg",
  ],
  ["https://humans.fyi/", "image/others.svg"],
  ["https://sitesee.co/", "image/others.svg"],
  ["https://uigarage.net/", "image/others.svg"],
  ["https://ecomm.design/", "image/others.svg"],
  ["https://www.designnominees.com/", "image/others.svg"],
  ["https://designvault.io/", "image/others.svg"],
  ["https://getcssscan.com/css-buttons-examples", "image/others.svg"],
  ["https://getcssscan.com/css-box-shadow-examples", "image/others.svg"],
  ["https://superdesigner.co", "image/others.svg"],
  ["https://landings.dev", "image/others.svg"],
  ["https://tinypng.com/", "image/others.svg"],
  ["https://imagecompressor.com/", "image/others.svg"],
  ["https://compressor.io/", "image/others.svg"],
  ["https://squoosh.app/", "image/others.svg"],
  ["https://bulkresizephotos.com/", "image/others.svg"],
  ["https://www.iloveimg.com/", "image/others.svg"],
  ["https://jakearchibald.github.io/svgomg/", "image/others.svg"],
  ["https://compressjpeg.com/", "image/others.svg"],
  ["https://compressnow.com/", "image/others.svg"],
  ["https://promo.com/tools/image-resizer/", "image/others.svg"],
  ["http://www.imageoptimizer.net/", "image/others.svg"],
  ["https://www.svgminify.com/", "image/others.svg"],
  ["http://jpeg-optimizer.com/", "image/others.svg"],
  ["https://resizing.app/", "image/others.svg"],
  ["https://ezgif.com/", "image/others.svg"],
  ["https://onlinepngtools.com/resize-png", "image/others.svg"],
  ["https://www.verexif.com/en/", "image/others.svg"],
  ["https://vecta.io/nano", "image/others.svg"],
  ["https://watermarkly.com/compress-jpeg/", "image/others.svg"],
  ["https://www.jpeg.io", "image/others.svg"],
  ["https://compressimage.io", "image/others.svg"],
  [
    "https://chrome.google.com/webstore/detail/whatfont/jabopobgcpjmedljpbcaablpmlmfcogm",
    "image/others.svg",
  ],
  [
    "https://chrome.google.com/webstore/detail/whatruns/cmkdbmfndkfgebldhnkbfhlneefdaaip?hl=en",
    "image/others.svg",
  ],
  [
    "https://chrome.google.com/webstore/detail/web-developer/bfbameneiokkgbdmiekhjnmfkcnldhhm",
    "image/others.svg",
  ],
  [
    "https://chrome.google.com/webstore/detail/awesome-screenshot-screen/nlipoenfbbikpbjkfpfillcgkoblgpmj?hl=en",
    "image/others.svg",
  ],
  [
    "https://chrome.google.com/webstore/detail/dailydev-news-for-busy-de/jlmpjdjjbgclbocgajdjefcidcncaied",
    "image/others.svg",
  ],
  [
    "https://chrome.google.com/webstore/detail/jsonview/chklaanhfefbnpoihckbnefhakgolnmc?hl=en",
    "image/others.svg",
  ],
  ["https://github.com/lauriro/json-lite", "image/others.svg"],
  [
    "https://chrome.google.com/webstore/detail/window-resizer/kkelicaakdanhinjdeammmilcgefonfh?hl=en",
    "image/others.svg",
  ],
  [
    "https://chrome.google.com/webstore/detail/responsive-viewer/inmopeiepgfljkpkidclfgbgbmfcennb?hl=en",
    "image/others.svg",
  ],
  [
    "https://chrome.google.com/webstore/detail/browserstack/nkihdmlheodkdfojglpcjjmioefjahjb?hl=en",
    "image/others.svg",
  ],
  [
    "https://chrome.google.com/webstore/detail/visbug/cdockenadnadldjbbgcallicgledbeoc?hl=en",
    "image/others.svg",
  ],
  [
    "https://chrome.google.com/webstore/detail/kontrast-wcag-contrast-ch/haphaaenepedkjngghandlmhfillnhjk?hl=en",
    "image/others.svg",
  ],
  [
    "https://chrome.google.com/webstore/detail/perfectpixel-by-welldonec/dkaagdgjmgdmbnecmcefdhjekcoceebi",
    "image/others.svg",
  ],
  [
    "https://chrome.google.com/webstore/detail/pesticide-for-chrome-with/neonnmencpneifkhlmhmfhfiklgjmloi",
    "image/others.svg",
  ],
  [
    "https://chrome.google.com/webstore/detail/site-palette/pekhihjiehdafocefoimckjpbkegknoh",
    "image/others.svg",
  ],
  [
    "https://chrome.google.com/webstore/detail/colorzilla/bhlhnicpbhignbdhedgjhgdocnmhomnp",
    "image/others.svg",
  ],
  [
    "https://chrome.google.com/webstore/detail/lorem-ipsum-generator-def/mcdcbjjoakogbcopinefncmkcamnfkdb?hl=en%20",
    "image/others.svg",
  ],
  [
    "https://chrome.google.com/webstore/detail/javascript-and-css-code-b/iiglodndmmefofehaibmaignglbpdald?hl=en",
    "image/others.svg",
  ],
  [
    "https://chrome.google.com/webstore/detail/imageye-image-downloader/agionbommeaifngbhincahgmoflcikhm",
    "image/others.svg",
  ],
  [
    "https://chrome.google.com/webstore/detail/gofullpage-full-page-scre/fdpohaocaechififmbbbbbknoalclacl",
    "image/others.svg",
  ],
  [
    "https://chrome.google.com/webstore/detail/stylebot/oiaejidbmkiecgbjeifoejpgmdaleoha",
    "image/others.svg",
  ],
  [
    "https://chrome.google.com/webstore/detail/colorpick-eyedropper/ohcpnigalekghcmgcdcenkpelffpdolg",
    "image/others.svg",
  ],
  [
    "https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi",
    "image/others.svg",
  ],
  [
    "https://chrome.google.com/webstore/detail/wappalyzer/gppongmhjkpfnbhagpmjfkannfbllamg",
    "image/others.svg",
  ],
  [
    "https://chrome.google.com/webstore/detail/fake-filler/bnjjngeaknajbdcgpfkgnonkmififhfo",
    "image/others.svg",
  ],
  [
    "https://chrome.google.com/webstore/detail/page-ruler-redux/giejhjebcalaheckengmchjekofhhmal",
    "image/others.svg",
  ],
  [
    "https://chrome.google.com/webstore/detail/web-editor/pdmlhckofhkhebmcplblcijijgjiakcm",
    "image/others.svg",
  ],
  [
    "https://chrome.google.com/webstore/detail/cssviewer/ggfgijbpiheegefliciemofobhmofgce",
    "image/others.svg",
  ],
  [
    "https://chrome.google.com/webstore/detail/fonts-ninja/eljapbgkmlngdpckoiiibecpemleclhh",
    "image/others.svg",
  ],
  [
    "https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk",
    "image/others.svg",
  ],
  [
    "https://chrome.google.com/webstore/detail/debug-css/igiofjnckcagmjgdoaakafngegecjnkj",
    "image/others.svg",
  ],
  [
    "https://chrome.google.com/webstore/detail/ux-check/giekhiebdpmljgchjojblnekkcgpdobp",
    "image/others.svg",
  ],
  [
    "https://chrome.google.com/webstore/detail/angular-devtools/ienfalfjdbdpebioblfackkekamfmbnh",
    "image/others.svg",
  ],
  [
    "https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en",
    "image/others.svg",
  ],
  [
    "https://chrome.google.com/webstore/detail/hackertabdev-developer-ne/ocoipcahhaedjhnpoanfflhbdcpmalmp",
    "image/others.svg",
  ],
  ["https://extract.pics/", "image/others.svg"],
  ["https://www.vertopal.com/", "image/others.svg"],
  ["https://everysize.kibalabs.com/", "image/others.svg"],
  ["https://devhints.io/", "image/others.svg"],
  ["https://thewebtoolbox.cc/", "image/others.svg"],
  ["https://webdevtrick.com/", "image/others.svg"],
  ["https://css-tricks.com/", "image/others.svg"],
  ["https://material.io/resources", "image/others.svg"],
  ["https://nodesign.dev", "image/others.svg"],
  ["https://a11ygator.chialab.io/", "image/others.svg"],
  ["http://commitizen.github.io/cz-cli/", "image/others.svg"],
  ["https://www.cleancss.com/", "image/others.svg"],
  ["https://tiny-helpers.dev/", "image/others.svg"],
  ["https://www.cssportal.com/css-ribbon-generator/", "image/others.svg"],
  ["https://caniuse.com/", "image/others.svg"],
  ["https://kangax.github.io/compat-table/es6/", "image/others.svg"],
  ["https://www.mydevice.io/", "image/others.svg"],
  ["https://codepen.io/", "image/others.svg"],
  ["https://responsively.app", "image/others.svg"],
  ["https://ekoopmans.github.io/html2pdf.js/", "image/others.svg"],
  ["https://cssreference.io/", "image/others.svg"],
  [
    "https://www.sitelocity.com/critical-path-css-generator",
    "image/others.svg",
  ],
  ["https://github.com/rossmoody/svg-gobbler", "image/others.svg"],
  ["https://shortcode.dev", "image/others.svg"],
  ["https://www.30secondsofcode.org/", "image/others.svg"],
  ["https://playcode.io/", "image/others.svg"],
  ["https://allthetags.com/", "image/others.svg"],
  ["https://vuetelemetry.com/", "image/others.svg"],
  ["https://gridjs.io/", "image/others.svg"],
  ["https://gerillass.com/", "image/others.svg"],
  ["https://www.sketchize.com/", "image/others.svg"],
  ["https://www.cssportal.com/", "image/others.svg"],
  ["https://devdocs.io/", "image/others.svg"],
  ["https://papersizes.io/", "image/others.svg"],
  ["http://flexboxfroggy.com/", "image/others.svg"],
  ["https://www.designbetter.co/books", "image/others.svg"],
  ["https://overapi.com/", "image/others.svg"],
  ["https://pageclip.co/", "image/others.svg"],
  ["https://shields.io", "image/others.svg"],
  ["http://williamsharkey.com/Shapes.html", "image/others.svg"],
  ["https://bootstrap-cheatsheet.themeselection.com/", "image/bootstrap.svg"],
  ["https://markodenic.com/tools/qr-code-generator/", "image/others.svg"],
  ["https://papersdb.com/", "image/others.svg"],
  ["https://www.setools.xyz/", "image/others.svg"],
  ["https://SmallDev.tools/", "image/others.svg"],
  ["https://angrytools.com/", "image/others.svg"],
  ["https://rapidapi.com/hub", "image/others.svg"],
  ["https://readme.so", "image/others.svg"],
  ["https://showcode.app", "image/others.svg"],
  ["https://www.tldraw.com", "image/others.svg"],
  ["http://marvelapp.github.io/devices.css/", "image/others.svg"],
  ["https://troopl.com", "image/others.svg"],
  ["https://apifox.cn", "image/others.svg"],
  ["https://piccalil.li/blog/a-modern-css-reset/", "image/others.svg"],
];

export const urlSVG = new Map(urls);
